"use client";

import { useSearchParams } from "next/navigation";
import { useState, useEffect } from "react";
import type { Problem, DiagnosticNode, Cause } from "@/lib/db/types";
import { DiagnosticTool } from "@/components/DiagnosticTool";
import Link from "next/link";

interface AIData {
  problem: Problem;
  nodes: DiagnosticNode[];
  causes: Cause[];
  source: string;
}

interface AIDiagnosticLoaderProps {
  slug: string;
}

export function AIDiagnosticLoader({ slug }: AIDiagnosticLoaderProps) {
  const searchParams = useSearchParams();
  const isAI = searchParams.get("ai") === "true";
  const originalQuery = searchParams.get("q") || slug.replace(/-/g, " ");
  const [data, setData] = useState<AIData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!isAI) return;

    let cancelled = false;

    const fetchAIDiagnostic = async () => {
      setLoading(true);
      setError("");
      try {
        const res = await fetch("/api/diagnostic", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ query: originalQuery }),
        });
        const result = await res.json();

        if (!cancelled) {
          if (result.source === "ai" && result.problem) {
            setData(result);
          } else {
            setError(result.message || "AI could not generate diagnostic.");
          }
        }
      } catch {
        if (!cancelled) {
          setError("Failed to fetch AI diagnostic.");
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };

    fetchAIDiagnostic();

    return () => {
      cancelled = true;
    };
  }, [isAI, originalQuery]);

  if (!isAI) return null;

  if (loading) {
    return (
      <div className="text-center py-12">
        <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mb-4"></div>
        <p className="text-gray-600">AI is generating your diagnostic tree...</p>
        <p className="text-sm text-gray-500 mt-2">This may take a few seconds.</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <div className="rounded-lg bg-yellow-50 border border-yellow-200 p-6 max-w-md mx-auto">
          <p className="text-yellow-800 font-medium mb-2">AI Diagnostic Unavailable</p>
          <p className="text-sm text-yellow-700 mb-4">{error}</p>
          <Link
            href="/search"
            className="inline-block rounded-lg bg-blue-600 px-4 py-2 text-white text-sm font-medium hover:bg-blue-700"
          >
            Try Another Search
          </Link>
        </div>
      </div>
    );
  }

  if (!data) return null;

  return (
    <div>
      <div className="rounded-lg bg-blue-50 border border-blue-200 p-4 mb-6">
        <p className="text-blue-800 text-sm">
          <span className="font-medium">AI-Generated Diagnostic:</span> This tree was generated by AI for your specific query. Results may vary.
        </p>
      </div>

      <header className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">{data.problem.title}</h1>
        <p className="mt-3 text-gray-600">{data.problem.description}</p>
      </header>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Symptoms</h2>
        <ul className="list-disc list-inside space-y-1 text-gray-700">
          {data.problem.symptoms.map((symptom) => (
            <li key={symptom}>{symptom}</li>
          ))}
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Diagnostic Tool</h2>
        <p className="text-gray-600 mb-6">
          Answer the following questions to help identify the cause of your problem.
        </p>
        <DiagnosticTool problem={data.problem} nodes={data.nodes} />
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">Possible Causes</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {data.causes.map((cause) => (
            <div
              key={cause.id}
              className="rounded-lg border border-gray-200 bg-white p-4"
            >
              <h3 className="font-semibold text-gray-900">{cause.title}</h3>
              <p className="mt-1 text-sm text-gray-600">{cause.description}</p>
              <p className="mt-2 text-sm text-blue-600">{cause.recommendation}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
